# Generated by Django 3.1.5 on 2021-05-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.TextField(max_length=100)),
                ('summary', models.TextField(max_length=200)),
                ('first_paragraph', models.TextField()),
                ('body', models.TextField()),
                ('author', models.ManyToManyField(to='author.Author')),
            ],
        ),
    ]
